### ISSUE TITLE
add current tab to tab group action

### ISSUE THREAD

**Issue by korhanozbek44** [bentodaniel/vs-tab-groups#1]
Hi. I think if add the currently visible tab to specific tab group actions it will be great.

**Comment by bentodaniel** [comment]
So, similarly to what happens when adding a tab to a group, where it displays all open tabs and all files in direcotry, but instead adds only the currently open tab and displays all groups so u can select to which u wanna add?

Or an action in the groups that instantly adds the currently open tab to said group?

**Comment by bobcat2085** [comment]
I think having the right-click on a tab context menu give you the option of adding the tab to a specific group or create a new group.
![image](https://user-images.githubusercontent.com/49205415/233203784-31d80ae0-a883-45d3-9592-d7799fbbe156.png)

Also, you could add an option to add all open tabs to a specific group or create a new group from the Open Editor options (ellipses) in the far right of the tab bar.
![image](https://user-images.githubusercontent.com/49205415/233203610-a1b6c7b9-4d99-4799-9209-d9ee81f61c85.png)
